
Microservice:
  Name: Micro-Database
  Version: 0.0.0
  Port: 9701

Production:
  Status: false
  FullPATH: key/server.crt   # ruta/fullchain.pem
  PrivPATH: key/server.key   # ruta/privkey.pem

ProtoGRPC:
  Port: 9702
